# 导航核心控制参数配置
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

controller_frequency: 10
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
recovery_behavior_enable: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 10.0
oscillation_distance: 0.3
planner_frequency: 0.5
max_planning_retries: -1.0

#详情参考wiki官方教程：http://wiki.ros.org/move_base