# 代价地图公有参数配置
#robot foorprint shape 机器人轮廓
footprint: [[0.15, 0.10], [-0.08, 0.10], [-0.08, -0.10], [0.15, -0.10]]
#plugins layers list
static_layer:    #静态层
  enable: true
  unknown_cost_value: -1 
  lethal_cost_threshold: 100
  map_topic: /map
  first_map_only: false
  subscribe_to_updates: true
  track_unknow_space: true
  use_maximum: false
  trinary_costmap: true

obstacle_layer: #障碍层
  enabled: true
  #Sensor management parameters
  observation_sources: laser_scan_sensor #point_cloud_sensor
  laser_scan_sensor:
    topic: /scan
    sensor_frame: /laser_link
    data_type: LaserScan
    clearing: true
    marking: true
    obstacle_range: 1.0  #障碍物探测范围
    raytrace_range: 2.0  #机器人运动过程中，实时清除代价地图中的障碍物
    track_unknow_space: true

global_inflation_layer: #全局膨胀层
  enabled: true
  inflation_radius: 0.15 #机器人和障碍物之间保持的最小距离
  cost_scaling_factor: 2.0

local_inflation_layer: #局部膨胀层
  enabled: true
  inflation_radius: 0.10 #机器人和障碍物之间保持的最小距离
  cost_scaling_factor: 5.0
#详情参考wiki官方教程：http://wiki.ros.org/costmap_2d
