#局部代价地图参数配置：
local_costmap:
   #Coordinate frame and tf parameters
   global_frame: /odom
   robot_base_frame: /base_footprint
   transform_tolerance: 2.0

   #Rate parameters
   update_frequency: 5.0 #发布信息的频率，也就是costmap可视化信息发布的频率
   publish_frequency: 5.0

   #map params
   static_map: false
   rolling_window: true #true:机器人在运动过程中，代价地图始终以机器人为中心
   width: 4.0
   height: 4.0
   resolution: 0.05 #代价地图的尺寸和分辨率

   #robot model
   inscribed_radius: 0.06
   circumscribed_radius: 0.09


   plugins:
      - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
      - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
